# -*- coding: utf-8 -*-
"""Linear Problem solving with SCIP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qmFIYAQy-IlYGXsxu0FIsoFpbx7j0Q6z

#Problem 1


Max: X+Y

Constraints:

-x+2y <= 8

2x+y <= 14

2x-y <= 10

0 <= x<= 10

0 <= y<= 10

#installation
"""

!pip install -q condacolab
import condacolab
condacolab.install()

!conda install pyscipopt

from pyscipopt import Model

model= Model('example')

#creating Variable

x=model.addVar('x')
y=model.addVar('y')

#objective

model.setObjective(x+y, sense='maximize')

#Constraints

model.addCons(-x+2*y <= 8)
model.addCons(2*x+y <= 14)
model.addCons(2*x-y <= 10)


model.optimize()

solution=model.getBestSol()

print('x:', solution[x])
print('y:', solution[y])